---
abstract: 'Takes the drudgery out of Exporting symbols'
author:
  - 'Fergal Daly <fergal@esatclear.ie>'
build_requires:
  Test::More: '0'
  base: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Exporter-Easy
requires:
  Exporter: '0'
  perl: '5.006'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Exporter-Easy
  repository: https://github.com/neilbowers/Exporter-Easy.git
version: '0.17'
